name: Packages
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)') || contains(github.event.schedule, '0 0 * * 0')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "15"
          registry-url: "https://registry.npmjs.org"

      - run: yarn
      - run: yarn pkg:build
      - run: yarn lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
